### ISSUE TITLE
OpenBSD mupdf search forward and backward does not work

### ISSUE THREAD

**Issue by bulibuta** [lervag/vimtex#1018]
I am having an issue similar to #117, but in my case xdotool works (see below). Compliation, pplatex quickfix window and everything else works except for mupdf forward and backward search. `\lv` starts the reader, but does not take me to the current page. If I hit the keys again, a new mupdf instance is started.

I am running OpenBSD -current on an amd64 machine with Vim 8.0.

xdotool works as expected with at least the following commands
```
$ xdotool search --class MuPDF
33554691
$ xdotool type --window 33554691 "2g"
$ xdotool type --window 33554691 "200g"
```

Also tried with this in `.latexmkrc`.

```perl
$pdflatex = 'pdflatex -synctex=1 --shell-escape %O %S';
$pdf_previewer = 'mupdf';
```

### Minimal working example

```tex
\documentclass{scrartcl}
\begin{document}
Word
\newpage
Word2
\end{document}
```

### Minimal vimrc file

```vim
set nocompatible
let &rtp = '~/.vim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable

let g:vimtex_quickfix_method = 'pplatex'
let g:latex_view_method = 'mupdf'
```

**Comment by lervag** [comment]
First, I took the liberty of simplifying your minimal example. Before we go more in depth, could you check if you are using the `clientserver` feature? You need to start vim with `vim --servername VIM` (`VIM` can be any name). It would also be helpful to get the output of `\li` after you have started compilation with `\ll`.

**Comment by lervag** [comment]
Please note that I've updated your minimal vimrc file, so please use the updated version.

Also, note that your `latexmkrc` file is not necessary, since you are setting things that vimtex will also set directly. Obv., it is useful for when you use latexmk from the terminal.

**Comment by bulibuta** [comment]
I am using servername VIM. Hope I got the cmd line right, it was really hard to copy over as it does not wrap. Thank you for looking into this!

```
System info
  OS: b_release: not found
  Vim version: VIM 8.0 (1-1255)
  Has clientserver: true
  Servername: VIM

vimtex project: vimtex
  base: vimtex.tex
  root: /home/bulibuta/tmp
  tex: /home/bulibuta/tmp/vimtex.tex
  out: /home/bulibuta/tmp/vimtex.pdf
  log: /home/bulibuta/tmp/vimtex.log
  aux: /home/bulibuta/tmp/vimtex.aux
  fls: /home/bulibuta/tmp/vimtex.fls
  document class: scrartcl
  packages:
    keyval
    scrbase
    scrkbase
    scrlfile
    tocbasic
    typearea
  compiler: latexmk
    backend: jobs
    output: /tmp/vurOq5z/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -synctex=1
        -interaction=nonstopmode
    job: process 17086 run
    cmd: max_print_line=2000 latexmk -verbose -pdf -synctex=1 -interaction=nonstopmode -pvc -e '$pdf_previewer = "mupdf"' -e '$success_cmd = "'""'vim'""'  --servername 'VIM' --remote-expr \"vimtex\#compiler\#callback(1)\""' -e '$failure_cmd = "'""'vim'""' --servername 'VIM' --remote-expr \"vimtex\#compiler\#callback(0)\""'  'vimtex.tex'
  viewer: General
    process: 
      pid: -
      cmd: mupdf '/home/bulibuta/tmp/vimtex.pdf' >/dev/null 2>&1 &
  qf: LaTeX logfile using pplatex
    setqflist: 53
```

**Comment by lervag** [comment]
You are not using the minimal vimrc file. From the output of `\li`, notice `viewer: General`. This implies that you are using the general method with `g:vimtex_view_general_viewer = 'mupdf'`, but this does not give the full features of the mupdf viewer.

**Comment by lervag** [comment]
I just pushed a commit that should give some more useful output for the `OS:` string in the `\li` output. I would be happy if you could verify that it works, as I don't have access to an OpenBSD system.

**Comment by bulibuta** [comment]
You were correct, I had to force a page refresh on github to get the new vimrc file. Sorry about that. I did update it and it still says `Viewer: General`.

**Comment by bulibuta** [comment]
Here is the output with the new commit you pushed. I think something is wrong.

```
System info
  OS: uname: unknown option -- o^@usage: uname [-amnprsv]
  Vim version: VIM 8.0 (1-1255)
  Has clientserver: true
  Servername: VIM

vimtex project: vimtex
  base: vimtex.tex
  root: /home/bulibuta/tmp
  tex: /home/bulibuta/tmp/vimtex.tex
  out: /home/bulibuta/tmp/vimtex.pdf
  log: /home/bulibuta/tmp/vimtex.log
  aux: /home/bulibuta/tmp/vimtex.aux
  fls: /home/bulibuta/tmp/vimtex.fls
  document class: scrartcl
  packages:
    keyval
    scrbase
    scrkbase
    scrlfile
    tocbasic
    typearea
  compiler: latexmk
    backend: jobs
    output: /tmp/vz044Bx/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -synctex=1
        -interaction=nonstopmode
    job: process 99574 run
    cmd: max_print_line=2000 latexmk -verbose -pdf -synctex=1 -interaction=nonst
  viewer: General
    process: 
      pid: -
      cmd: xdg-open '/home/bulibuta/tmp/vimtex.pdf' >/dev/null 2>&1 &
  qf: LaTeX logfile using pplatex
    setqflist: 53
```

**Comment by lervag** [comment]
Ah, I'm blind. You are setting `g:latex_view_method`, but it should be `g:vimtex_view_method`.

**Comment by lervag** [comment]
Also, I pushed a new update for the OS. I think it should print something now.

**Comment by bulibuta** [comment]
I think you want `uname -s`.

**Comment by lervag** [comment]
Hmm. I thought `uname -a` was available on OpenBSD. How about `uname -rs`? It should show the OS type and kernel?

**Comment by bulibuta** [comment]
Ugh, sorry about that typo. Now there is only one mupdf instance when I hit `\lv` (new ones are no longer spawned), but it still does not go to the right page.

**Comment by bulibuta** [comment]
`uname -a` is fine.

**Comment by bulibuta** [comment]
New output is much nicer and contains mupdf.

```
System info
  OS: OpenBSD sci.irofti.net 6.2 GENERIC.MP#246 amd64
  Vim version: VIM 8.0 (1-1255)
  Has clientserver: true
  Servername: VIM

vimtex project: vimtex
  base: vimtex.tex
  root: /home/bulibuta/tmp
  tex: /home/bulibuta/tmp/vimtex.tex
  out: /home/bulibuta/tmp/vimtex.pdf
  log: /home/bulibuta/tmp/vimtex.log
  aux: /home/bulibuta/tmp/vimtex.aux
  fls: /home/bulibuta/tmp/vimtex.fls
  document class: scrartcl
  packages:
    keyval
    scrbase
    scrkbase
    scrlfile
    tocbasic
    typearea
  compiler: latexmk
    backend: jobs
    output: /tmp/vss4fFD/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -synctex=1
        -interaction=nonstopmode
    job: process 58639 run
    cmd: max_print_line=2000 latexmk -verbose -pdf -synctex=1 -interaction=nonst
  viewer: MuPDF
    xwin id: 29360387
    process: 
      pid: -
      cmd: mupdf  '/home/bulibuta/tmp/vimtex.pdf' >/dev/null 2>&1 &
    cmd_synctex_view: synctex view -i 6:3:'/home/bulibuta/tmp/vimtex.tex' -o '/h
  qf: LaTeX logfile using pplatex
    setqflist: 58
```

**Comment by lervag** [comment]
If `uname -sr` works, then I think that might be the better choice, since it shows kernel and OS.

With MuPDF, you should be able to do forward search with `\lv` (that is, it should go to the correct page), and backward search _from vim_ with `\lr`. Do any of these work?

**Comment by bulibuta** [comment]
```
$ uname -sr
OpenBSD 6.2
```

**Comment by lervag** [comment]
Perfect, thanks! I've tested this also on Ubuntu and OpenSUSE, as well as Arch Linux, and it seems `uname -sr` is ubiquitous. I'll change and push now.

**Comment by bulibuta** [comment]
None of those work (`\lv` or `\lr`).

**Comment by bulibuta** [comment]
`xwin id` is the same as `xdotool search --class MuPDF`

**Comment by lervag** [comment]
Strange. It's hard to debug when I can't reproduce. So, these features rely on synctex. Is `synctex` available on your system`?

Also, after doing `\lv`, what is the output of `\li`, specifically the `viewer` sections?

**Comment by bulibuta** [comment]
`cmd_getpage` also seems fine in terminal.

**Comment by bulibuta** [comment]
```
$ synctex 
This is SyncTeX command line utility, version 1.3
```

**Comment by bulibuta** [comment]
```
  viewer: MuPDF
    xwin id: 29360387
    process: 
      pid: -
      cmd: mupdf  '/home/bulibuta/tmp/vimtex.pdf' >/dev/null 2>&1 &
    cmd_synctex_view: synctex view -i 4:2:'/home/bulibuta/tmp/vimtex.tex' -o '/home/bulibuta/tmp/vimtex.pdf' | grep -m1 'Page:' | sed 's/Page://' | tr -d '^@'
    cmd_getfile: synctex edit -o "2:288:108:/home/bulibuta/tmp/vimtex.pdf"| grep 'Input:' | sed 's/Input://' | head -n1 | tr -d '^@' 2>/dev/null
    cmd_getline: synctex edit -o "2:288:108:/home/bulibuta/tmp/vimtex.pdf"| grep -m1 'Line:' | sed 's/Line://' | head -n1 | tr -d '^@'
    cmd_getpage: xdotool getwindowname 29360387 | sed 's:.* - \([0-9]*\)/.*:\1:' | tr -d '^@'
```

**Comment by bulibuta** [comment]
I think I found an issue: `grep: unknown option -- m`

**Comment by lervag** [comment]
If you are able, perhaps you could do some `echo` debugging on your side` The relevant code is in `autoload/vimtex/view/mupdf.vim`, and you want to look at the `forward_search(outfile)` and `reverse_search()` functions.

**Comment by lervag** [comment]
Ah...

**Comment by lervag** [comment]
Do you have any `--max-count` option for grep on openbsd?

**Comment by bulibuta** [comment]
[Nope](https://man.openbsd.org/grep) :(

**Comment by bulibuta** [comment]
So do I have to add `-m` to grep or can we work around that? (I am an OpenBSD developer.)

**Comment by lervag** [comment]
Obv., if `-m` was available for grep on OpenBSD, then that would be much simpler for me. However, I could also try to change the current vimtex behaviour. `grep -m1 ...` should be equivalent to something like `grep ... | head -n1`, I think. Are you able to test this on your end? It feels sort of heavy to have a test cycle where I push code and you test and report...

**Comment by bulibuta** [comment]
I started modifying our grep to add `-m` support. Once finished it has to go through review and there is a chance it will not get accepted. Either way, I will test with `head -n1` and get back to you. Thank you very much for your support!

**Comment by bulibuta** [comment]
`head -n1` solves the issue for me for both `\lv` and `\lr`. This is great!

**Comment by bulibuta** [comment]
I can keep this as a local modification until I add `-m` support to our `grep(1)`. If, due to politics and what not, it fails to get in the tree, I will be back with an OpenBSD specific patch. Thanks again!

**Comment by lervag** [comment]
No problem, happy to help. It's also interesting to get verified that vimtex works as expected on OpenBSD.

Btw: I used MuPDF for some time myself, and I like it, but I changed to Zathura. You might also find Zathura to be interesting. It has more Vim like key bindings and better support for synctex. I assume it should also work on OpenBSD.

**Comment by bulibuta** [comment]
Thank you for the tip!

I will try Zathura when I get some free time. So far I used xpdf with pdflatex (now replaced with mupdf thanks to vimtex), okular for annotation (replaced with evince because it okuar currently segfaults with multiple tabs on OpenBSD). So a fifth pdf reader probably makes sense in my ecosystem :)

In the meantime I sent out the grep -m diff and you can follow the [review](https://marc.info/?l=openbsd-tech&m=151266103717983&w=2) process if you want.

**Comment by lervag** [comment]
Yeah, it seems there are quite a few pdf viewers where each has its strengths. Zathura is good with vimtex, I think, but not really good for annotations and similar.

And cool about the grep review process. Seems like a relevant thing to add to OpenBSD.

**Comment by bulibuta** [comment]
I just added [-m support](https://marc.info/?l=openbsd-cvs&m=151284472600731&w=2) to [OpenBSD grep](https://man.openbsd.org/grep), so this issue can be closed.

Thank you once again for the impeccable support!

**Comment by lervag** [comment]
Cool! I'm happy to hear that this investigation lead to an improvement to grep on OpenBSD. And I'm always happy to help fellow vimmers :)

Btw, fascinating to see a project use CVS for version control. But I guess "when it works why fix it"?

**Comment by bulibuta** [comment]
Well CVS is really annoying when it comes to history. Or anything else for that matter. I hope to see it replaced soon, but that is just my personal opinion.
