### ISSUE TITLE
:h vimtex doesn't seem to work

### ISSUE THREAD

**Issue by j2kun** [lervag/vimtex#1516]
**Issue**
:h vimtex cannot find docs.

**minimal.vim**
  ```vim
  set nocompatible
  let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
  let &runtimepath .= ',~/.vim/bundle/vimtex/after'
  filetype plugin indent on
  syntax enable
  ```

**minimal.tex**
  ```tex
  \documentclass{minimal}
  \begin{document}
  Hello world!
  \end{document}
  ```

**Commands/Input**
Vim started with
```
vim -u minimal.vim minimal.tex
```

Run:

```
:h vimtex
```

**Observed Behaviour**
E149: Sorry, no help for vimtex

**Expected Behaviour**
Shows vimtex documentation

**Output from VimtexInfo**
```
System info
  OS: Mac OS X 10.14.6 (18G87)
  Vim version: VIM 8.1 (1-1750)
  Has clientserver: false

vimtex project: minimal
  base: minimal.tex
  root: /Users/jeremy/mip-source
  tex: /Users/jeremy/mip-source/minimal.tex
  out: 
  log: 
  aux: 
  fls: 
  compiler: latexmk
    backend: jobs
    output: /var/folders/k2/xw116qj50n96tn37lvfc6rrm0000gn/T/vpWbTTi/0
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: minimal
```

**Comment by lervag** [comment]
How did you install vimtex? For several years most people installed with a plugin manager like vim-plug, but I've become aware that a lot of people are now using Vims builtin package feature. This method does not automatically create the helptag file, and so doing `:helptags` should fix the issue for you.

Can you confirm?

**Comment by slonik-az** [comment]
I would suggest doing
```:helptags ALL```
to (re)generate help files for all active plugins.

**Comment by j2kun** [comment]
`:helptags ALL` did the trick. You learn something new about vim every day :)

Thanks!

**Comment by TSSlade** [comment]
I installed vimtex via vim-plug, had the same issue as j2kun - :helptags ALL did not resolve the issue.

Instead it provides `E152: Cannot open /usr/share/vim/vim81/doc/tags for writing`

Not sure how to provide the output of Vimtexinfo as he did above - given guidance, happy to provide it.

**Comment by lervag** [comment]
If you install with vim-plug, then this should "just work". I suspect it is not properly installed. What is the output of doing `:VimtexInfo` after you open a LaTeX file?

**Comment by TSSlade** [comment]
`E492:  Not an editor command: VimtexInfo` upon typing `:VimtexInfo` within a file `minimal.tex` containing
```
1 \documentclass{minimal}
2 \begin{document}
3 Hello world!
4 \end{document}
```

**Comment by lervag** [comment]
Well, then vimtex is not properly installed. If you want help, then open a new issue and give a full description.
