### ISSUE TITLE
E475: texMathSuper "(" Contained conceal cchar

### ISSUE THREAD

**Issue by The-nth-Term** [lervag/vimtex#1923]
I was using an older version of vimtex since the summer (I believe 1.3), and I updated the plugin last night without thinking (Using vim-plug) to the latest version. Now any time I open my projects I get this error. Is there a way to access older versions of the plugin to before I got the error? Or is there something wrong with my _vimrc? I'm not super experienced in debugging this kind of thing, and I can't seem to find any help in the docs of this plugin or vimplug.

The relevant bits of my _vimrc are:
```vim
call plug#begin('C:\Program Files (x86)\Vim\vim82\Plugged')

" Latex Compiling plugin VimTex
Plug 'lervag/vimtex'
let g:tex_flavor='latex'
" let g:vimtex_view_method = 'SumatraPDF'
let g:vimtex_quickfix_mode=0
" set conceallevel=1
" let g:tex_conceal='abdmg'
```

I am looking to set up concealment for the first time, and it wasn't working, which is how I updated it. I installed another plugin, and updated all plugins, which is how I accidentally updated this one. But then that broke things worse, so I uninstalled it, and now regardless of whether or not the concealling lines are commented out I still get the issue.

The specific error message I get looks like this:
![VimError](https://user-images.githubusercontent.com/54423878/104818843-630d6a80-5800-11eb-917c-b33b223d2374.png)

(:checkhealth was not a valid command, and :Vimtex_Compile_Output was blank)

**Comment by lervag** [comment]
> I was using an older version of vimtex since the summer (I believe 1.3), and I updated the plugin last night without thinking (Using vim-plug) to the latest version. Now any time I open my projects I get this error. Is there a way to access older versions of the plugin to before I got the error?

Yes, you can do `Plug 'lervag/vimtex', {'branch': 'v1.3'}` (or any other version, see `git tag` in the vimtex repo for a list of available tags).

If you do stay on the new version, then note that `g:tex_flavor` is no longer necessary to set manually, and `g:tex_conceal` does not have any effect in Vimtex (see the release notes for version 2.0).

> The specific error message I get looks like this: ...

The error is probably due to encoding. I've pushed a possible fix, please test (update with e.g. `:PlugUpdate lervag/vimtex` or in the Git repo with `git pull`).

> (:checkhealth was not a valid command, and :Vimtex_Compile_Output was blank)

`:checkhealth` is available in neovim, and `:VimtexCompileOutput` (without the underscores) is relevant only to see compilation output.

**Comment by The-nth-Term** [comment]
So I updated your plugin again via ```vim :PlugUpdate```, and now I still get the same error, but this time with a different character.

![VimError2](https://user-images.githubusercontent.com/54423878/104828138-6fafb400-583c-11eb-9907-6c8e99539a6e.png)

As for downgrading, I had a bit of trouble for a minute, but I had to comment out all of the vimtex pieces in the _vimrc, run ```vim :PlugClean```, and then uncomment it out with the branch tag on the end. This fixed the problem, and all the files now open correctly on version 1.3.

**Comment by lervag** [comment]
> So I updated your plugin again via `vim :PlugUpdate`, and now I still get the same error, but this time with a different character.

Strange. Things should work, and if you care to provide a minimal working example that reproduces the issue I will be glad to investigate further.

> As for downgrading, I had a bit of trouble for a minute, but I had to comment out all of the vimtex pieces in the _vimrc, run `vim :PlugClean`, and then uncomment it out with the branch tag on the end. This fixed the problem, and all the files now open correctly on version 1.3.

Or, of course, you can just stay at an older version, if that is what you want.

**Comment by The-nth-Term** [comment]
So I'm a little confused here, I did some playing around trying to find a minimal example, and it's very minimal indeed. I cleaned everything out except what was there when I first opened the vimrc, and plugging vimtex. I still get the same looking error, with the only difference being `30_match_math` instead of `31_match_math`.
My _vimrc now only contains
```vim
source $VIMRUNTIME/vimrc_example.vim

call plug#begin('C:\Program Files (x86)\Vim\vim82\Plugged')

Plug 'lervag/vimtex'

call plug#end()

" Use the internal diff if available.
" Otherwise use the special 'diffexpr' for Windows.
if &diffopt !~# 'internal'
  set diffexpr=MyDiff()
endif
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg1 = substitute(arg1, '!', '\!', 'g')
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg2 = substitute(arg2, '!', '\!', 'g')
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let arg3 = substitute(arg3, '!', '\!', 'g')
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  let cmd = substitute(cmd, '!', '\!', 'g')
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction
```
And a simple LaTeX Document looks like
```LaTeX
\documentclass{minimal}
\begin{document}

This is some text. Also, some math: $2\cdot3=6$.

\end{document}
```
I feel like it's probably something local if I can make it that minimal, but I am not doing but installing vim-plug and vimtex, so I have no idea what it might be.

**Comment by The-nth-Term** [comment]
I solved it! I didn't have my encoding specified in my _vimrc file, so adding it removed the errors! And I can also update to the latest version now!

Explicitly, I added the line ```set encoding=utf-8``` after installing vimtex but before enabling concealment. (If that matters)

**Comment by lervag** [comment]
Great, and thanks for providing the solution that works for you. I'd suggest that as the next step. I'll also look into if it is possible to fix things so `set encoding=utf-8` is not necessary.
