### ISSUE TITLE
PDF not refreshing after continuous update with build_dir set

### ISSUE THREAD

**Issue by evesdropper** [lervag/vimtex#2449]
### Description

I'm not quite sure if this is a VimTeX or Zathura issue, but for some reason, VimTeX updates don't show on Zathura after tabbing out. This is a bit of a heisenbug in my opinion - sometimes it occurs and other times it is fine.  If it doesn't seem to be a VimTeX issue or can't be reproduced, feel free to close and I'll open an issue in Zathura.

This only occurred after I set `let g:vimtex_compiler_latexmk = { 'build_dir' : 'out' }` - changing the build dir to out to support putting auxiliary files elsewhere and also set `[outputdir=out]` for the `minted ` package to move listings there. Perhaps it has to do with setting the output dir combined with the `:VimtexView` hook from [here](https://github.com/lervag/vimtex/issues/1719).

### Steps to reproduce

`minimal.vim`
```vim
call plug#begin()
Plug 'lervag/vimtex'
call plug#end()

let g:tex_flavor = 'latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
let g:vimtex_compiler_progname = 'latexmk'
let g:vimtex_compiler_engine = 'lualatex'
let g:vimtex_compiler_latexmk = { 'build_dir' : 'out' }
" auto show PDF
function! ZathuraHook() dict abort
    if self.xwin_id <= 0 | return | endif
    silent call system('xdotool windowactivate ' . self.xwin_id . ' --sync')
    silent call system('xdotool windowraise ' . self.xwin_id)
endfunction
augroup vimrc_vimtex
    autocmd!
    autocmd User VimtexEventView call ZathuraHook()
augroup END
set conceallevel=1
```
`test2.tex`
```LaTeX
\documentclass{article}
    \usepackage[outputdir=out]{minted}
\begin{document}
Add some new text.
\[
    x + y = 10 \, \mathbf{bold text} \, \mathit{italic text} \, \mathrm{math text} 
\]
Test.

\begin{minted}{python}
x = 1
\end{minted}

Time to return back to neovim.
```

~~Not sure if this changes if I'm using pdfLaTeX~~ EDIT: this also has the same behvaior when using pdfLaTeX.
1. `nvim -u minimal.vim test2.tex`
2. `:VimtexCompile`
3. Go away for a little - e.g. tab out, browse something else.
4. Edit some text and save.

### Expected behavior

The output PDF should be updated.

### Actual behavior

No change to the PDF unless I poke Zathura by doing things such as changing window size or zooming in/out.

Sometimes the text looks fine; other times it gets ugly (missing letters, copies incorrectly).

![image](https://user-images.githubusercontent.com/82856360/182508244-b9c05d07-a086-45fe-96b1-d34fa09767a5.png)

The original text was "Does this work with pdftex?" but it was cut off.

### Do you use a latexmkrc file?

Yes. Not sure if it's too relevant - I use TeXLive, so `auxdir` setting wouldn't apply to me.

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.4 LTS
  Vim version: NVIM v0.7.2
  Has clientserver: true
  Servername: /tmp/nvimAnECUB/0

VimTeX project: test2
  base: test2.tex
  root: /mnt/c/Users/user/Documents/university
  tex: /mnt/c/Users/user/Documents/university/test2.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsgen amsmath amsopn amstext calc catchfile etexcmds etoolbox
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: out
    callback: 1
    continuous: 1
    executable: latexmk
    job:
      jobid: 6
      output: /tmp/nvimAnECUB/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -inte
      pid: 7323
  viewer: Zathura
    xwin id: 4194307
    cmd_start: zathura  -x "/squashfs-root/usr/bin/nvim --headless -c \"VimtexInv
  qf method: LaTeX logfile
```

**Comment by lervag** [comment]
> I'm not quite sure if this is a VimTeX or Zathura issue, but for some reason, VimTeX updates don't show on Zathura after tabbing out. This is a bit of a heisenbug in my opinion - sometimes it occurs and other times it is fine. If it doesn't seem to be a VimTeX issue or can't be reproduced, feel free to close and I'll open an issue in Zathura.

Let's find out. Or, at least, I'll try and help :)

> This only occurred after I set `let g:vimtex_compiler_latexmk = { 'build_dir' : 'out' }` - changing the build dir to out to support putting auxiliary files elsewhere and also set `[outputdir=out]` for the `minted ` package to move listings there.

Ok, so: this only happens for projects with `minted`?

> Perhaps it has to do with setting the output dir combined with the `:VimtexView` hook from [here](https://github.com/lervag/vimtex/issues/1719).

Yes, perhaps; I have some suggestions to your vim config. Let's start there. The following is a new `minimal.vim` that should be equivalent to the one you provided, except somewhat fixed/improved. Notice that you used some options that were not necessary or that did not exist. Also, I believe your `ZathuraHook` function is now fixed.

```viml
call plug#begin()
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_view_method = 'zathura'
let g:vimtex_quickfix_mode = 0

" This specifies to use -lualatex by default
let g:vimtex_compiler_latexmk_engines = { '_' : '-lualatex' }
let g:vimtex_compiler_latexmk = { 'build_dir' : 'out' }

function! ZathuraHook() abort
    " Get the viewer xwin_id
    let xwin_id = exists('b:vimtex.viewer.xwin_id')
            \ ? b:vimtex.viewer.xwin_id
            \ : 0
    if xwin_id <= 0 | return | endif

    silent call system('xdotool windowactivate ' . xwin_id . ' --sync')
    silent call system('xdotool windowraise ' . xwin_id)
endfunction

augroup vimrc_vimtex
    autocmd!
    autocmd User VimtexEventView call ZathuraHook()
augroup END
```

> ~Not sure if this changes if I'm using pdfLaTeX~ EDIT: this also has the same behvaior when using pdfLaTeX.

Yes, I would be surprised if `lualatex` vs `pdflatex` had any effect here. This is more likely due to VimTeX and/or latexmk and Zathura (or only Zathura).

> No change to the PDF unless I poke Zathura by doing things such as changing window size or zooming in/out.
> 
> Sometimes the text looks fine; other times it gets ugly (missing letters, copies incorrectly).

It's strange. My intuition is that this is not really VimTeX, but I'm not sure.

> ### Do you use a latexmkrc file?
> 
> Yes. Not sure if it's too relevant - I use TeXLive, so `auxdir` setting wouldn't apply to me.

Could you list the contents of your `.latexmkrc` file?

**Comment by evesdropper** [comment]
I haven't really used LaTeX for work until recently, but it seems like when I was compiling this time, some of the same issues persisted (frozen screen, bugged letters when poking Zathura), but I was able to force reload Zathura and generate the correct output (previously it was jammed and pressing R did not do anything). I guess it was some sort of strange heisenbug; I can't really figure out the root of it (which program is causing the problem), why it started, and why it only happened on WSL on my new computer, but not on WSL on my old computer or on Linux. I think it would make sense to close it until I find out more information about this strange behavior and can replicate it on any of my other environments.

I appreciate the help though :smile:

**Comment by lervag** [comment]
Sounds good! Feel free to reopen or open a new issue if/when you have more information!
