### ISSUE TITLE
Paragraph motions behave badly

### ISSUE THREAD

**Issue by anjiro** [lervag/vimtex#318]
Vimtex remaps `{` and `}` for reasons that aren't explained in the documentation. Unfortunately, this causes non-standard behavior. For example, `2}` moves only one paragraph down, and `d}` in the middle of a line, rather than deleting from the cursor's location, deletes from the beginning of the line. These strange behaviors of course affect all commands involving movement, making it difficult to shift multiple paragraphs left and right with e.g. `<3}`.

**Comment by lervag** [comment]
I've updated so that `{` and `}` accepts a count. This should solve the issue.

**Comment by lervag** [comment]
I also fixed a minor error in the operator pending map.

**Comment by anjiro** [comment]
Fantastic, that fixes it! Thanks for the fast response.

**Comment by lervag** [comment]
No problem, thanks for noticing and reporting!

**Comment by anjiro** [comment]
Still a problem:

	\begin{marginfigure}
		\begin{minipage}{\marginparwidth}
			\includegraphics{images/cats.jpg}
		\end{minipage}
	\end{marginfigure}

On line 1, using `}` just moves to line 2 rather than to the end of the paragraph. A second `}` moves to line 4, and the final `}` moves to the last line. But `d3}` on the first line doesn't delete the whole thing, just the first line.

**Comment by lervag** [comment]
Interesting. I'll look into it.

Note that we are currently discussing how the paragraph motions and text objects should work in #318. You are welcome to join the discussion.

**Comment by Rmano** [comment]
@lervag  --- do you mean in #320 I suppose ;-)

**Comment by lervag** [comment]
Yes, sorry! :)
