### ISSUE TITLE
Compiling doesn't work anymore since commit 8ae3cea

### ISSUE THREAD

**Issue by mbrunnen** [lervag/vimtex#424]
Since you fixed issue #382, vimtex is not able to compile anymore. I am using Gvim on Windows.
![issue](https://cloud.githubusercontent.com/assets/8393339/14321665/7a790216-fc1a-11e5-96d1-48c364a849fb.png)

**Comment by lervag** [comment]
I think this may be because you have `set shellslash` in your vimrc file. If I am right, then I think I have an idea for how to fix this (temporarily disable shellslash).

**Comment by mbrunnen** [comment]
Yes, shellslash is set, by python-mode, though. I put setlocal noshellslash in my ftplugin-dir and no it works. Now it works :)

**Comment by lervag** [comment]
I'm curious: I should either comment on this in the docs, or I should update the code so that it works also with `shellslash` enabled. The latter is more bullet proof, but it also adds entropy...

**Comment by fuzzybear3965** [comment]
`shellslash` should be supported. Note that if you (read: we) want to start cleaning up and making paths more uniform: Windows accepts forward slashes in the paths. I don't know of any "gotchas" when it comes to using forward slashes for paths. Also, in case someone's path has a mixture of forward and back slashes, one can make the path uniformly "forward" or backward" with `substitute(expand(resolve('C:/Some\Path/String'),':p'),'\\','\/','g')`. This becomes `C:/Some/Path/String`. You may find this helpful.

**Comment by lervag** [comment]
For this issue, I am a little bit dependent on windows users explaining what is not working when `shellslash` is activated.

**Comment by fuzzybear3965** [comment]
What, specifically, would be helpful for you in determining what is happening? Would `b:vimtex.cmd_latexmk-compile` be all that you need (assuming a minimal working example and `vimrc` + `:set shellslash`)?

**Comment by lervag** [comment]
First: The basics, I need to know _what_ the problem is, I need the minimal example, the minimal vimrc, and steps to reproduce the problem. The output from `:VimtexInfo` is always helpful.

**Comment by mbrunnen** [comment]
Here is a MWE:
`vimrc`:
```
set nocompatible
set shellslash

" Load Vimtex
let &rtp  = $HOME . '\vimfiles\bundle\vimtex,' . &rtp
let &rtp .= ',' . $HOME . '\vimfiles\bundle\vimtex\after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:tex_flavor='latex'
let g:vimtex_latexmk_continuous=0
let g:vimtex_latexmk_background=0
let g:vimtex_mappings_enabled=1
let g:vimtex_latexmk_build_dir='build'
let g:vimtex_view_general_viewer = 'SumatraPDF'
```

`main.tex`:
```
\documentclass{article}
\usepackage{subfiles}

\title{Test file.}
\author{Tester Testington}

\begin{document}
\maketitle
\section{Test without subfile}
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
\end{document}
```

1. Open the `main.tex`
2. Run `:VimtexCompile`

Then I get:
![issue_error](https://cloud.githubusercontent.com/assets/8393339/14427448/1a32a702-fff5-11e5-86ac-b67ec4d2407f.png)

And `:VimtexInfo` returns:
![issue_info](https://cloud.githubusercontent.com/assets/8393339/14427465/333c991a-fff5-11e5-9906-4d412324c64e.png)

**Comment by lervag** [comment]
Great, thanks! Do you know any other things that break with `shellslash` set? I would suspect perhaps `:VimtexClean` and `VimtexCompileSS`.

**Comment by lervag** [comment]
Ok, I think the latest commit should fix this issue. Please test.

**Comment by mbrunnen** [comment]
1. `:VimtexCompileSS` don't works, there is no message and no output. `:VimtexClean` works.
2. You fixed it!

**Comment by lervag** [comment]
Hmm... That's strange. I'll look into it. I must admit I didn't remember to test with `VimtexCompileSS`, as I was sure it would work. I think there must be something else happening here, actually.

**Comment by lervag** [comment]
With me, `VimtexCompileSS` works as expected on windows with the above minimal vimrc and minimal example. Note, though, that there is currently no status message from this command, which might be confusing.

Thus, if you first clean all files, then do `:VimtexCompileSS`, then the files should be generated as expected, but there will be no feedback. Can you verify this?

I will push an update quite soon with a simple status message after compilation in order to provide some minimal feedback.

**Comment by lervag** [comment]
I just pushed an update that improves the `VimtexCompileSS` functionality. It should now provide feedback to the user. If the comilation is run in foreground, then the status message will indicate if there are errors or not (you should still use `\le` to open the quickfix window). If the process runs in the background (this needs manual setting of `g:vimtex_latexmk_background`, then vimtex can not currently help and will simply state that compilation has started.

**Comment by mbrunnen** [comment]
I've tested it again. On Commit 2a83d4a with this MWE VimtexCompileSS doesn't produce any valueable output. The build folder has two files (attachment), and `\le` is not working either, since there isn't a log file either. `\lo` gives an empty output. May be it's my latexmk, but `VimtexCompile` just works fine.
[main.aux.txt](https://github.com/lervag/vimtex/files/216561/main.aux.txt)
[main.fdb_latexmk.txt](https://github.com/lervag/vimtex/files/216562/main.fdb_latexmk.txt)
![vimtexinfo](https://cloud.githubusercontent.com/assets/8393339/14486188/eddeca24-015b-11e6-8858-2522ee15d9d0.png)

**Comment by lervag** [comment]
Could you test with the most recent version? I think I found a minor bug that could prevent compilation...

**Comment by mbrunnen** [comment]
I tested now the most recent commit 9dfa9af and building works now. `\lo` still don't give me any output, though. Actually, `:VimtexCompileSS` worked already good on my normal configuration.

**Comment by lervag** [comment]
No, `\lo` will only give any output of `g:vimtex_latexmk_background = 1`, which you must set explicitly. The reason is that `\lo` will show the output that has been redirected, but when the process runs in the foreground, there will be no redirection.
